---
title: "TRGN 515: Advanced Human Genomic Analysis Methods"
subtitle: "Spring 2026 | University of Southern California"
format:
  html:
    toc: false
---

## Course content

Below is the schedule of modules, slides, and assignments for the semester. 
Links will be updated as we progress through the course.

| Module | Slides | Assignment | Due Date |
|:---|:---:|:---:|:---|
| **Module 1: Sequencing Technologies**<br>Overview of NGS, Nanopore, and PacBio. | [{{< fa tv >}} HTML](slides/1_seq_techs.html)<br>[{{< fa file-pdf >}} PDF](slides/1_seq_techs.pdf) | [{{< fa pen-to-square >}} Assignment 1](modules/1_sequencing_techs/1_sequencing_techs.qmd) | **02/27/2026** |
| **Module 2: Structural Variant Detection**<br>Definition and types of structural variants (SV), detection of indels and SV. | [{{< fa tv >}} HTML](slides/2_sv.html)<br>[{{< fa file-pdf >}} PDF](slides/2_sv.pdf) | [{{< fa pen-to-square >}} Assignment 2](modules/2_sv/2_sv.qmd) | **03/10/2026** |
| **Module 3: Variant Functional Annotation**<br>Variant effect prediction. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Assignment 3](modules/3_annotation/3_annotation.qmd) | **03/31/2026** |
| **Module 4: Genome Assembly**<br>Introduction to genome assembly. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Assignment 4](modules/4_assembly/4_assembly.qmd) | **04/10/2026** |
| **Module 5: Epigenetics - Methylation**<br>Methylation detection with 3rd Generation sequencing. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Assignment 5](modules/5_base_mods/5_base_mods.qmd) | **04/21/2026** |
| **Module 6: Metagenomics**<br>Introduction to metagenomics, 16S amplification, and taxonomy. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Assignment 6](modules/6_metagenomics/6_meta.qmd) | **TBD** |
| **Additional dataset 1: COLO-829**<br>Analysis of cancer dataset. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Assignment 7](modules/7_colo829/7_colo829.qmd) | **TBD** |
| **Final assignment**<br>Dataset for the final assignment. | [{{< fa tv >}} HTML](#)<br>[{{< fa file-pdf >}} PDF](#) | [{{< fa pen-to-square >}} Final assignment](modules/final_assignment/final.qmd) | **05/11/2026** |

: {tbl-colwidths="[40,15,20,25]" .table .table-hover}