---
title: "Assignment 5: Nanopore base modifications"
author: Arturo Torres Ortiz
date: 03/31/2026
format:
  html:
    toc: true
    code-copy: true
    theme: cosmo
    highlight-style: github
  pdf:
    include-in-header: ../../header.tex
    callout-icon: false
    callout-appearance: default
    geometry:
      - top=30mm
      - left=20mm
---

For this assignment, we will perform differential methylation analysis using single-molecule direct DNA methylation detection from Nanopore sequencing. We will use data generated via Cas9-targeted Nanopore sequencing (nCATS) to compare the methylation profiles of a normal breast epithelial cell line (MCF-10A) against a highly aggressive triple-negative breast cancer cell line (MDA-MB-231). The files used for the assignment and their SRA accessions are summarized in the following table:

| Cell Line | Status | Library | SRA accession |
| :--- | :--- | :--- | :--- |
| MCF-10A | Normal breast epithelial | MinION nCATS (10 gene panel) | SRX7698109 |
| MDA-MB-231 | Breast cancer (TNBC) | MinION nCATS (10 gene panel) | SRX7698110 |

The original reference paper for this dataset:

* Gilpatrick, T., Lee, I., Graham, J.E. et al. Targeted nanopore sequencing with Cas9-guided adapter ligation. Nat Biotechnol 38, 433–438 (2020). https://doi.org/10.1038/s41587-020-0407-5

The authors developed a targeted enrichment strategy that yields extremely high sequencing coverage over specific cancer-associated loci, allowing for highly accurate, native DNA methylation profiling without the need for bisulfite conversion.

We will process the raw Nanopore signal data to identify Differentially Methylated Regions (DMRs) linked to cancer development, specifically focusing on the GSTP1 and KRT19 genes.


# Learning objectives
At the end of this week's assignment you will be able to:

1. Be familiar with single-molecule direct DNA methylation detection
2. Methylation aware asecalling from Nanopore raw signal  
3. Be able to extract methylation levels from BAM files
4. Know how to visualize methylation data
5. Be able to identify differentially methylated regions (DMRs)

# Input and outputs

The input for this assignment are the fast5 files generated by Nanopore from normal breast tissue (MCF-10A cell line) and Triple-Negative Breast Cancer (MDA-MB-231 cell line). This dataset was generated using Cas9-targeted Nanopore sequencing (nCATS), and Cas9 was used to cut and enrich specific genes before sequencing. This data is publicly available with accession number PRJNA531320.

> fast5 files:
>
> `/project2/msalomon_1816/trgn_515/5_base_mods/fast5`


You can download the data from here as well:

> Normal sample:
>
> wget https://sra-pub-src-1.s3.amazonaws.com/SRR11047866/TG_02_Mcf10a_brPanel_MinION_fast5.tgz.2

> Tumor sample:
>
> wget https://sra-pub-src-1.s3.amazonaws.com/SRR11047865/TG_03_MdaMb231_brPanel_MinION_fast5.tgz.2

# Required software
In order to complete the assignment, you can use this conda environments I prepared:

```sh
conda activate /project2/msalomon_1816/trgn_515/conda_env/trgn515
```

# Converting fast5 to pod5 format

<!-- Because these are single file fast5, run this with the ont-fast5-api software:
single_to_multi_fast5 -i fast5/MCF-10A/ -s fast5_multi/MCF-10A/ -n 4000 --recursive -t 10
single_to_multi_fast5 -i fast5/MDA-MB-231/ -s fast5_multi/MDA-MB-231/ -n 4000 --recursive -t 10
-->

The two most common ONT raw signal file formats are:

1. Fast5 is the original raw signal data from ONT. This file format has been replaced, but it's still found in many ONT runs done before 2022. For a comprehensive guide on the fast5 format: https://hasindu2008.github.io/slow5specs/fast5_demystified.pdf
2. Pod5 is the new ONT format, based on Apache arrow-columnal format. More information here: https://pod5-file-format.readthedocs.io/en/0.3.2/SPECIFICATION.html

New softare works better (and sometimes even requires!) pod5 files, so the first thing we are going to do is to transformed our fast5 files into pod5. ONT provides the software `pod5` to do exactly this:

```sh
conda activate /project2/msalomon_1816/trgn_515/conda_env/pod5

pod5 convert fast5
-t $SLURM_CPUS_PER_TASK # Multithreading
-r # Search files recursively
--output /path/to/pod5/data.pod5 # Output Pod5
/path/to/fast5/ # Folder with fast5
```

# Basecalling with Dorado

Dorado is the current ONT basecaller. It is optimized to run in GPU, especially Nvidia A100 and H100 GPU cards. To request an interactive GPU in CARC:

```sh
salloc --partition=gpu --ntasks=1 --gpus-per-task=a100:1 --mem=30G --time=1:00:00
```

You will also need to load some modules from the CUDA toolkit. To do that:

```sh
module load gcc/13.3.0
module load cuda/12.6.3
```

For more information on GPU programming in CARC, visit https://www.carc.usc.edu/user-guides/advanced-hpc-programming/gpu-programming

```sh
conda activate /project2/msalomon_1816/trgn_515/conda_env/trgn515

dorado_bin=/project2/msalomon_1816/trgn_515/5_base_mods/dorado-0.9.6/bin/dorado
reference=/project2/msalomon_1816/trgn_515/5_base_mods/ref_genome/genome.fa
pod5_dir=/path/to/pod5
bam_dir=/path/to/bam

# The path to the model for basecalling
model_dir=/project2/msalomon_1816/trgn_515/5_base_mods/dorado-0.9.6/models/dna_r9.4.1_e8_sup@v3.3

# The path to the model for modified bases basecalling
mod_model_dir=/project2/msalomon_1816/trgn_515/5_base_mods/dorado-0.9.6/models/dna_r9.4.1_e8_sup@v3.3_5mCG_5hmCG@v0

# We need to use an older version of dorado for this dataset, and for that we need to build a container to make it work in our CARC cluster
module load apptainer # Loading Apptainer to build the container

# The Apptainer wrapper (using Ubuntu 22.04 to guarantee glibc compatibility)
# --nv tells it to use the cluster's GPUs
# --bind makes sure the container can see your /project2 files
dorado="apptainer exec --nv --bind /project2:/project2 docker://ubuntu:22.04 $dorado_bin"

$dorado basecaller $model_dir $pod5_dir/file.pod5 -v --reference $reference --mm2-opts "-x asm10" --modified-bases-models $mod_model_dir > $bam_dir/file.bam

# You already know how to do the next two steps!
samtools sort ...
samtools index ...
```

### Task 1: Basecalling with modified bases
::: {.callout-note}
1) What is the output of the basecalling when using modified bases? **(5pts)**
2) Why do you think they have chosen this file type? **(5pts)**
3) What are the tags that represent methylation, and what do each of them mean? **(5pts)**
4) In our Dorado command, we passed the argument `-r sup,5mCG_5hmCG`. What does `sup` and `5mCG_5hmCG` mean? **(10pts)**
5) Why have we chosen `5mCG_5hmCG` for a human dataset? **(10pts)**
:::


# Mapping to the reference genome

We have already aligned our reads to the reference genome, but if you hadn't done this, you would need to convert your SAM file into fastq.

```sh
samtools fastq -@ 5 -T "*" $bam_dir/M13363.sam > /path/to/fastq/M13363.fastq
```

Once we have fastq files, we can map them with minimap.

```sh
reference=/project2/biodb/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

minimap2 -ax splice \
-y
$reference /path/to/fastq/M13363.fastq | \
samtools sort -o $bam_dir/M13363.bam -
```


### Task 2: Mapping modified reads.
::: {.callout-note}
1) What does the -T flag in `samtools fastq` do and why is it important? **(5pts)**
2) What does the -y (lower case!) flag in `minimap2` do and why is it important? **(5pts)**
:::

# Extract modified base information from BAM file

We are going to use ModKit to analyze methylation data. The pileup subcommand runs through all sites or motifs and generates a probability that the site is modified.

You need to run this both for your normal and tumor samples.

```sh
modkit=/project2/msalomon_1816/trgn_515/5_base_mods/modkit-0.6.1/modkit
reference=/project2/biodb/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

$modkit pileup
--cpg # Restrict analysis to CpG sites
--combine-strands # Combine methylation for the forward and reverse strand
--reference <reference.fa> # Reference genome
--modified-bases 5mC 5hmC # Specified the inferred modified bases
<file.bam> # Input BAM file
<file.bed> # Output bed file

bgzip -k <file.bed> # Note you can also pipe the output of modkit into bgzip
tabix -p bed <file.bed.gz>
```

The `modkit` software allows for filtering of methylation calls using `--filter-threshold` for general filtering and `--mod-thresholds` for modified base filtering.

You can find the modified codes in Table 1. If no thresholds are specified, ModKit will calculate the appropiate threshold by taking a sample of the BAM file and calculating the 10th percentile of the probability distribution.

**Table 1: Modified Base codes** *(source: https://samtools.github.io/hts-specs/SAMtags.pdf)*

| Unmodified base | Code | Abbreviation | Name | ChEBI |
| :--- | :--- | :--- | :--- | :--- |
| **C** | m | 5mC | 5-Methylcytosine | 27551 |
| | h | 5hmC | 5-Hydroxymethylcytosine | 76792 |
| | f | 5fC | 5-Formylcytosine | 76794 |
| | c | 5caC | 5-Carboxylcytosine | 76793 |
| | C | Ambiguity code | any C mod | - |
| **T** | g | 5hmU | 5-Hydroxymethyluracil | 16964 |
| | e | 5fU | 5-Formyluracil | 80961 |
| | b | 5caU | 5-Carboxyluracil | 17477 |
| | T | Ambiguity code | any T mod | - |
| **U** | U | Ambiguity code | any U mod | - |
| **A** | a | 6mA | 6-Methyladenine | 28871 |
| | A | Ambiguity code | any A mod | - |
| **G** | o | 8oxoG | 8-Oxoguanine | 44605 |
| | G | Ambiguity code | any G mod | - |
| **N** | n | Xao | Xanthosine | 18107 |
| | N | Ambiguity code | any mod | - |



### Task 3: Make a pileup of the methylation calls
::: {.callout-note}
Let ModKit calculate the filtering thresholds.

The output of this analysis is a `bedMethyl` file, which it's just a normal bed file with some extra columns.

1) What are the columns of the resulting file? Visit https://github.com/nanoporetech/modkit for more information **(5pts)**
2) Can you think on some filters that may be important given the provided columns? **(5pts)**
3) Open the resulting BED file and look at the first few rows. How many rows are generated for each single genomic position, and what specific column differentiates them? Based on our ModKit command, why is the file structured this way? How many rows do you expect per genomic position? **(5pts)**
4) Look at column 11 (fraction modified). If a genomic region is fully methylated on both alleles, you would expect a value near 100%. What biological scenario would result in a fraction of ~50%? **(5pts)**
5) What column would you use to identify different methylation patterns in each allele? How would a heterozygous methylation pattern look like? **(5pts)**
6) Why do we run `bgzip` and `tabix` on the resulting BED file before moving to the next step? What do these tools do? **(5pts)**
:::

<!-- 1) If you did NOT use the `--combine-strands` flag, how many rows would you expect to see for a single CpG site, and why? **(5pts)** -->

<!-- Heterozygosity / Allele-Specific Methylation, Imprinting, or a mixed cell population/tumor heterogeneity -->

# Differential methylation analysis (DMR)

In differential methylation analysis, we perform a statistical test (eg: t-test) to find differences in methylation patterns between samples (eg: normal vs tumour).

We will stay within ModKit, which uses a binomial distribution to find differential methylation. In our example, we have a cancer/normal pair.


## Analyze modified bases at specific locations

If you are not interested in genome wide methylation patterns, it may be handy to subset methylation in specific regions. For human, common regions of interest would be CpG islands.

You can get a list of CpG islands from the UCSC genome browser:

```sh
wget -qO- http://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/cpgIslandExt.txt.gz \
   | gunzip -c \
   | awk 'BEGIN{FS="\t"; OFS="\t"} NR>1 {print $2, $3, $4, $5}' \
   | bedtools sort -i - > cpg_islands_ucsc.bed
```

Because we are working with a targeted sequencing panel (nCATS) rather than Whole Genome Sequencing, we do not want to scan the entire genome or every single CpG island. Instead, we will restrict our analysis to the specific genes targeted by our panel.

You can find those genes in this bed file:

```
regions=/project2/msalomon_1816/trgn_515/5_base_mods/bed/gene_targets.bed
```

Now, we can pass this target file to `modkit dmr pair` using the `-r` flag. This will extract the methylation probabilities from both of our pileup files and calculate the statistical difference only at these specific loci.

```sh
regions=/project2/msalomon_1816/trgn_515/5_base_mods/bed/gene_targets.bed
reference=/project2/biodb/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

$modkit dmr pair
  -a ${norm_pileup}.gz # Bed with methylation from sample 1
  -b ${tumor_pileup}.gz # Bed with methylation from sample 2
  -o <out_file.bed> # Output to stdout if not present
  -r ${regions} # List of regions in BED format
  --ref <reference.fa> # Reference genome
  --base C # may be repeated if multiple modifications are being used
  --threads <n_threads> # Number of threads

```


### Task 4: Interpreting the DMR Output
::: {.callout-note}

Review the resulting bed file and consult the ModKit documentation if necessary.

1) Which column in the output file represents the actual difference in methylation fractions between the normal and tumor samples? **(5pts)**
2) Look at the data for the  region. Does this gene show hypermethylation (increased methylation) or hypomethylation (decreased methylation) in the tumor sample compared to the normal sample? **(5pts)**
3) Why is it statistically more robust to calculate differential methylation across a region (like a CpG island or promoter) rather than looking at individual, isolated cytosines? **(5pts)**
:::


<!-- ## Analyze modified bases at every position

If we want to get methylation patters at every position, we can skip the `--ref` option.

```sh
modkit=/project/msalomon_1385/TRGN_515/6_base_mods/modkit_v0.4.4/modkit
reference=/project2/biodb/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa

$modkit dmr pair
  -a ${norm_pileup}.gz # Bed with methylation from sample 1
  -b ${tumor_pileup}.gz # Bed with methylation from sample 2
  -o <out_file.bed> # Output to stdout if not present
  --ref <reference.fa> # Reference genome
  --base C # may be repeated if multiple modifications are being used
  --threads <n_threads> # Number of threads
  --log-filepath <log_file> # Path to log file
``` -->

## Visualize modified bases on IGV

During class, we will see how to visualize methylaytion data in IGV. Use what we learn to answer the following questions:

::: info
**Task 5: Visualize modified variants.**

Select a region from your differential methylation output (either the CpG islands or single base) and show it in IGV.

1) What are the different colors showing? **(5pts)**
2) Are there any differences between the tumor sample and the control? **(5pts)**
3) Is the tumor sample hypermethylated or hypomethylated compared to the control? Make a quick reference search to find what's the common pattern. **(5pts)**
:::

# Phasing of long reads

Phasing refers to the process of determining which alleles (genomics variants) are inherited together, identifying the parental origin of each allele and separating maternally and paternally inherited copies of each chromosome into haplotypes to get a complete picture of genetic variation. Variants within the same copy of a chromosome are in “cis”, while those from different copies are in “trans”.

Phasing can be done by looking at the heterozygous calls in a VCF that co-occur within the same read. To do that, we will use `WhatsHap`.

First, we phase the variants within the VCF file:

```sh
whatshap phase
--ignore-read-groups # Adding this because in our examples sample names in BAM and VCF do not match
-o <output.vcf> # Output VCF file
--reference=<reference.fa> # Reference genome
<input_vcf> # Input VCF file
<input_bam> # Input BAM file
```

Once we have the phased variants, we can find out which reads within a BAM file belong to each haplotype. We will add a haplotype tag to each read individually. 

```sh
whatshap haplotag
--ignore-read-groups
-o <out_bam> # Output BAM file
--reference=<reference.fa> # Reference genome
--output-threads=<n_threads> # Threads for BAM compression
<input_phased_vcf> # Input phased VCF file
<input_bam> # Input BAM file
```